-- Our own copy of the DiscIt catalog. User traffic never leaves this table.
create table disc (
    id             varchar(64)  primary key,
    name           varchar(200) not null,
    brand          varchar(120) not null,
    category       varchar(80)  not null,
    speed          double precision not null,
    glide          double precision not null,
    turn           double precision not null,
    fade           double precision not null,
    stability_label varchar(60),
    name_slug      varchar(200),
    brand_slug     varchar(120),
    image_url      varchar(512),
    source_url     varchar(512),
    active         boolean      not null default true,
    content_hash   varchar(64),
    first_seen_at  timestamptz  not null default now(),
    last_synced_at timestamptz  not null default now()
);

create index disc_active_speed_idx on disc (active, speed);
create index disc_name_lower_idx on disc (lower(name));
create index disc_brand_lower_idx on disc (lower(brand));

-- Plastic is not published by DiscIt, so the blend axis is curated here.
create table plastic_type (
    id              bigint generated by default as identity primary key,
    brand           varchar(120)  not null,
    name            varchar(120)  not null,
    slug            varchar(120)  not null,
    family          varchar(32)   not null,
    stability_shift double precision not null default 0,
    durability      integer       not null,
    grip            integer       not null,
    description     varchar(1024) not null,
    constraint plastic_type_brand_slug_uq unique (brand, slug),
    constraint plastic_type_durability_ck check (durability between 1 and 5),
    constraint plastic_type_grip_ck check (grip between 1 and 5),
    constraint plastic_type_family_ck check
        (family in ('BASE', 'MID', 'PREMIUM', 'GRIPPY_PREMIUM', 'GUMMY', 'GLOW', 'SPECIALTY'))
);

create index plastic_type_slug_idx on plastic_type (lower(slug));
