-- Physical bags (the backpack/cart), as distinct from the discs that go in them.
--
-- Nothing upstream publishes this: DiscIt covers molds only, and manufacturers describe bags in
-- marketing copy rather than a feed. Capacity and empty weight are what make "is this bag
-- overpacked" and "which bag fits my lineup" answerable at all.
--
-- Dimensions stay in inches because every source publishes them that way and converting would
-- introduce rounding for no gain; weights are grams to match `disc`, where grams is the universal
-- unit in the sport.
create table bag_model (
    id                 bigint generated by default as identity primary key,
    brand              varchar(120)  not null,
    model              varchar(160)  not null,
    slug               varchar(200)  not null,

    -- Capacity is a range because most makers quote one ("holds 8-12 discs").
    disc_capacity_min  integer,
    disc_capacity_max  integer       not null,

    empty_weight_grams integer,
    height_in          numeric(5, 2),
    width_in           numeric(5, 2),
    depth_in           numeric(5, 2),
    carry_on_compliant boolean,
    price_usd          numeric(8, 2),

    -- A lighter bag is not automatically a better swap: build quality differs. Surfaced alongside
    -- weight so a comparison can say so instead of implying lightest wins.
    build_tier         varchar(16)   not null default 'MID',
    bag_type           varchar(16)   not null default 'BACKPACK',

    -- Provenance, because this table is seeded from hand research and will later be refreshed from
    -- manufacturer sites. Knowing which rows are which decides what a sync may overwrite.
    source             varchar(32)   not null default 'MANUAL_RESEARCH',
    source_url         varchar(512),
    notes              varchar(1024),

    active             boolean       not null default true,
    first_seen_at      timestamptz   not null default now(),
    last_synced_at     timestamptz   not null default now(),

    constraint bag_model_brand_slug_uq unique (brand, slug),
    constraint bag_model_capacity_ck check (disc_capacity_max >= 1
        and (disc_capacity_min is null or disc_capacity_min <= disc_capacity_max)),
    constraint bag_model_weight_ck check (empty_weight_grams is null or empty_weight_grams between 100 and 20000),
    constraint bag_model_tier_ck check (build_tier in ('BUDGET', 'MID', 'PREMIUM')),
    constraint bag_model_type_ck check (bag_type in ('BACKPACK', 'SHOULDER', 'CART', 'DUFFLE')),
    constraint bag_model_source_ck check (source in ('MANUAL_RESEARCH', 'SCRAPED', 'MANUFACTURER_FEED'))
);

create index bag_model_capacity_idx on bag_model (active, disc_capacity_max);
create index bag_model_brand_idx on bag_model (lower(brand));
